# /etc/slurm/cgroup.conf
# Resource enforcement via Linux cgroups

CgroupAutomount=yes
ConstrainCores=yes
ConstrainRAMSpace=yes
ConstrainDevices=yes
AllowedRAMSpace=100
AllowedSwapSpace=0
MaxRAMPercent=95
